# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=300)),
                ('mobile_no', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999L), django.core.validators.MinValueValidator(1000000000)])),
                ('blood_group', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
