# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
