# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_auto_20170622_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'../Images/profile/index.jpeg', null=True, upload_to=b'profile'),
        ),
    ]
