# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 05:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999L), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
