# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 8)),
        ),
    ]
