# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0002_auto_20170622_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_note',
            name='doctor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brand_names',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Doctor'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_amt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.IntegerField(blank=True, help_text='No of times a day'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_date',
            field=models.DateField(blank=True, help_text='Start date of the prescription'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='method',
            field=models.CharField(blank=True, choices=[(b't', b'Tablet'), (b'p', b'Powder'), (b'l', b'Liquid'), (b'i', b'Inhaler'), (b'o', b'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='overdose_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='possible_sideeffects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='usage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine_note',
            name='medicine_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='tests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sypmtom_videos',
            name='symptom_video',
            field=models.URLField(blank=True),
        ),
    ]
