# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0003_auto_20170622_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_date',
            field=models.DateField(blank=True, help_text='Date the disease was acquired'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Medicine'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Procedure'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Symptom'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disease_note',
            name='disease_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='bodypart',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Bodypart'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Doctor'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Medicine'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='possible_complication',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='symptom',
            field=models.ManyToManyField(blank=True, to='MyHealthApp.Symptom'),
        ),
        migrations.AlterField(
            model_name='procedure_images',
            name='procedure_image',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AlterField(
            model_name='procedure_note',
            name='procedure_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure_videos',
            name='procedure_video',
            field=models.URLField(blank=True),
        ),
    ]
