# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0004_auto_20170622_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure_images',
            name='procedure_image',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
    ]
