# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0004_auto_20170622_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='premium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='blood_sugar',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
