# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0005_auto_20170622_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='MyHealthApp.Doctor'),
        ),
    ]
