# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0005_auto_20170622_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodypart',
            old_name='bodypartname',
            new_name='bodypart',
        ),
        migrations.AlterField(
            model_name='procedure_images',
            name='procedure_image',
            field=models.ImageField(null=True, upload_to='procedures'),
        ),
    ]
