# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0006_auto_20170627_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_phone_number',
        ),
    ]
