# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=1000)),
                ('bodypart', models.ManyToManyField(to='MyHealthApp.Bodypart')),
                ('medicines', models.ManyToManyField(to='MyHealthApp.Medicine')),
            ],
        ),
    ]
