# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0010_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('possible_complication', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=b'')),
                ('video', models.FileField(upload_to=b'')),
                ('bodypart', models.ManyToManyField(to='MyHealthApp.Bodypart')),
                ('medicine', models.ManyToManyField(to='MyHealthApp.Medicine')),
                ('symptom', models.ManyToManyField(to='MyHealthApp.Symptom')),
            ],
        ),
    ]
