# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0011_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='bodypart',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='bodypart',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='medicines',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Bodypart',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
