# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0015_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodypart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.ManyToManyField(to='MyHealthApp.Medicine')),
            ],
        ),
    ]
