# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0022_auto_20170613_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypart',
            name='bodypart',
            field=models.CharField(choices=[('head', 'Head'), ('abdomen', 'Abdomen'), ('arms', 'Arms'), ('chest', 'Chest'), ('feet', 'Feet'), ('hands', 'Hands'), ('hips', 'Hips'), ('legs', 'Legs'), ('neck', 'Neck'), ('pelvis', 'Pelvis'), ('shoulder', 'Shoulder')], default='head', max_length=15),
        ),
    ]
