# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0023_bodypart_bodypart'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='measurement',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
