# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyHealthApp', '0024_auto_20170613_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
