# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyHealthApp', '0025_auto_20170613_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='medicine',
        ),
    ]
